roles/provision_vm/README.md, tests/integration/targets/prepare_soap/tasks/main.yml
Updated the provision_vm_guest_id description to point to vSphere 7.0
=> ACA-1303: Fix description link in provision_vm role README file

changelogs/fragments/20__mm-feature__add-provision-virtual-esxi.yml, changelogs/fragments/mm-feature__add-provision-virtual-esxi.yml, roles/provision_virtual_esxi/README.md, roles/provision_virtual_esxi/defaults/main.yml, roles/provision_virtual_esxi/tasks/deploy_new_esxi_hosts.yml, roles/provision_virtual_esxi/tasks/main.yml, tests/integration/targets/provision_virtual_esxi_test/mock_side_effects.yml, tests/integration/targets/provision_virtual_esxi_test/run.yml, tests/integration/targets/provision_virtual_esxi_test/runme.sh, tests/integration/targets/provision_virtual_esxi_test/tasks/main.yml, tests/integration/targets/provision_virtual_esxi_test/vars/main.yml
Split this from my old PR because it got too large.
-----
This change includes a new role to deploy ESXi hosts as virtual machines on an existing VCenter or physical ESXi host. 
The role takes a reduced set of hardware parameters and X number of VM names from the user. It checks for these X number of ESXi VMs and uses the hardware specification to create any that are missing. Some hardware settings are not parameterized and are based on VMWare recommendations or requirements.
Newly created VMs expect a mounted ESXi ISO file. The ISO used for the install should be configured for unattended install, but the user can manually complete the install if desired and the playbook will just wait for them to finish. ISO files are expected to be located on a datastore and that file path is passed in …
=> add provision_virtual_esxi

changelogs/fragments/32__mm-bugfix__provision_virtual_esxi.yml, roles/provision_virtual_esxi/README.md, roles/provision_virtual_esxi/tasks/main.yml, tests/integration/targets/provision_virtual_esxi_test/vars/main.yml
- Added missing variable documentation
- Removed an old variable from a name refactor. The new variable name was already marked as mandatory
=> fix missing docs and redundant vars

changelogs/fragments/38__mm-bugfix__provision-vcenter-use-mac-bin-to-deploy.yml, roles/provision_vcenter/tasks/deploy_from_iso.yml, roles/provision_vcenter/tasks/main.yml, roles/provision_vcenter/tasks/os_specific_iso_actions/mount_darwin.yml, roles/provision_vcenter/tasks/os_specific_iso_actions/unmount_darwin.yml, roles/provision_vcenter/vars/main.yml
This PR changes the VCSA binary used to deploy vcenter when on mac vs linux operating systems. It also simplifies the mounting mechanism for macs since the previous method caused occasional file system read issues
=> make mac OS use correct binary to deploy vcenter

.github/workflows/test.yml, Makefile, README.md, changelogs/fragments/39__mm-feature__cluster-settings.yml, execution-environment/execution-environment.yml, galaxy.yml, playbooks/cluster_settings.yml, roles/cluster_settings/README.md, roles/cluster_settings/defaults/main.yml, roles/cluster_settings/tasks/main.yml, tests/integration/requirements.txt, tests/integration/requirements.yml, tests/integration/targets/cluster_settings_test/run.yml, tests/integration/targets/cluster_settings_test/runme.sh, tests/integration/targets/cluster_settings_test/tasks/main.yml, tests/integration/targets/cluster_settings_test/vars/main.yml
Adding playbook and role to manage cluster settings for a vCenter cluster.
The user can optionally modify DRS, DRM, vCLS, HA, and vSAN settings on their cluster. Each group of settings can be configured, enabled/disabled, or omitted independently.
I added a playbook for general settings. I will add another playbook specifically for modifying HA status under another ticket.
I was not able to add integration tests for the vSAN settings due to a required SDK that can only be downloaded from VMWare with a customer login. Im making followup tickets to research ways around that
=> Mm feature/cluster settings

.github/workflows/eco-vcenter-ci.yaml, CODEOWNERS, Makefile, changelogs/fragments/42__eco-vcenter-ci-integration.yml, tests/integration/generate_integration_config.sh, tests/integration/integration_config.yml.tpl, tests/integration/requirements.txt, tests/integration/targets/info_test/defaults/main.yml, tests/integration/targets/info_test/run.yml, tests/integration/targets/info_test/runme.sh, tests/integration/targets/info_test/vars.yml, tests/integration/targets/init.sh, tests/integration/targets/prepare_rest/tasks/main.yml, tests/integration/targets/prepare_soap/tasks/main.yml
This PR is the first step to establish a CI in upstream (similar CI will be opened for vmware.vmware repo), that runs the integration tests on the real vcenter environment we have behind redhat vpn.
**Few notes:**
- This PR includes the action itself, some enhancements and modifications to the current info test we have in the 
integration folder. the intention is to do the same for the rest of the integration tests (existing and new ones) one by 
one, so that they could run both on vcsim (or as rest calls) and on the real vcenter env.
- In order for the PR to work, and so does others, I'll need to request to add the following secrets github env to the current repo: VCENTER_HOSTNAME, VCENTER_PASSWORD, VCENTER_USERNAME. I'll need dev for that, so will ask one of you for a help with that …
=> add first integration CI test to run on eco vcenter

tests/integration/targets/vmware_ops_content_library_test/tasks/get_content_library_info.yml, tests/integration/targets/vmware_ops_content_library_test/tasks/main.yml, tests/integration/targets/vmware_ops_content_library_test/vars/main.yml
Adding checks to assert that the content library has been created with the given parameters. 
Depends on [PR 51](https://github.com/redhat-cop/cloud.vmware_ops/pull/51)
=> Add verification step to content_library integration tests

changelogs/fragments/47__mm_feature__add_manage_folder.yml, playbooks/manage_folder.yml, roles/manage_folder/README.md, roles/manage_folder/defaults/main.yml, roles/manage_folder/tasks/main.yml, roles/manage_folder/tasks/manage_path_part.yml, tests/integration/targets/manage_folder_test/run.yml, tests/integration/targets/manage_folder_test/runme.sh, tests/integration/targets/manage_folder_test/tasks/main.yml, tests/integration/targets/manage_folder_test/vars/main.yml
Allows a user to create or delete a folder tree in vmware, or create just the final folder in a tree. For example
Create any missing folders along the path `/DC01/vms/my/production/web`
Or just create the folder `web` in the already existing path `/DC01/vms/my/production`
=> add role to manage folders

changelogs/fragments/62__mm-feature_provision_template.yml, playbooks/provision_vm/manage_template.yml
Adding playbook to create a template from a VM, or a completely new template.
I think leveraging the existing provision_vm role makes sense instead of creating a new role for this, but having a dedicated playbook may make it easier for a user to create a template if they are unfamiliar with content/just looking at the list of available playbooks in AAP.
There are some additional validation steps that could be added as a pre_tasks or in a standalone role, but they are situational I think. Like, if a user is converting an existing VM to a template they need to power it off first. We could check that as part of this playbook but not every user would need or maybe even want that.
=> Mm feature/aca 1592 create vm template

changelogs/fragments/73__mm-feature_add_provision_vm_template_opt.yml, playbooks/provision_vm/manage_template.yml, playbooks/provision_vm/manage_vm.yml, roles/provision_vm/README.md, roles/provision_vm/defaults/main.yml, roles/provision_vm/tasks/main.yml
Previously, the playbook to provision a new template used the wrong variable. The option to create a template in the provision_vm role also was not exposed.
This change exposes that option but leaves the default as false to maintain the old behavior. I explicitly set this variable in the manage_vm and manage_template playbooks
=> add provision_vm_is_template option

changelogs/fragments/77__mm-bugfix_remove_template_playbook.yml, playbooks/provision_vm/manage_template.yml
QE identified an issue where the vmware_guest module does not execute the `is_template` option. So this playbook does not do what is expected
=> removing vm template playbook

tests/integration/targets/runme.sh, tests/integration/targets/vmware_ops_cluster_settings_test/tasks/main.yml, tests/integration/targets/vmware_ops_cluster_settings_test/vars/main.yml, tests/integration/targets/vmware_ops_content_library_test/tasks/main.yml, tests/integration/targets/vmware_ops_content_library_test/vars/main.yml, tests/integration/targets/vmware_ops_deploy_ovf_test/tasks/main.yml, tests/integration/targets/vmware_ops_deploy_ovf_test/vars/main.yml, tests/integration/targets/vmware_ops_esxi_maintenance_mode_test/tasks/add_or_remove_resource_pool.yml, tests/integration/targets/vmware_ops_esxi_maintenance_mode_test/tasks/main.yml, tests/integration/targets/vmware_ops_esxi_maintenance_mode_test/vars/main.yml, tests/integration/targets/vmware_ops_export_vm_as_ovf_test/tasks/main.yml, tests/integration/targets/vmware_ops_export_vm_as_ovf_test/vars/main.yml, tests/integration/targets/vmware_ops_manage_folder_test/tasks/main.yml, tests/integration/targets/vmware_ops_manage_folder_test/vars.yml, tests/integration/targets/vmware_ops_manage_folder_test/vars/main.yml, tests/integration/targets/vmware_ops_provision_virtual_esxi_test/runme.sh, tests/integration/targets/vmware_ops_provision_virtual_esxi_test/tasks/cleanup_esxi.yml, tests/integration/targets/vmware_ops_provision_virtual_esxi_test/vars/main.yml, tests/integration/targets/vmware_ops_provision_vm_test/tasks/main.yml, tests/integration/targets/vmware_ops_provision_vm_test/tasks/post_update_settings_validation.yml, tests/integration/targets/vmware_ops_provision_vm_test/vars/main.yml, tests/integration/targets/vmware_ops_snapshot_management_test/vars/main.yml, tests/integration/targets/vmware_ops_vcenter_host_connection_test/tasks/main.yml, tests/integration/targets/vmware_ops_vcenter_host_connection_test/tasks/manage_resource_pool.yml, tests/integration/targets/vmware_ops_vcenter_host_connection_test/vars/main.yml
Jira ticket - [ACA-1695](https://issues.redhat.com/browse/ACA-1695)
Changes included (separated by commits):
- Added `retries` to eliminate random failures
- Fixed `always` block for `vmware_ops_manage_folder_test`
- Added `ignore_errors` to `cleanup_esxi.yml` of `vmware_ops_provision_virtual_esxi_test`
- Added `tiny_prefix` to isolate test runs
- Fixed assertion in `vmware_ops_provision_vm_test`
=> Improve vmware_ops integration tests cleanup implementation

changelogs/fragments/90__add_ntp_var.yml, roles/provision_vcenter/README.md, roles/provision_vcenter/defaults/main.yml, roles/provision_vcenter/templates/config_parts/vm.j2
Add `provision_vcenter_vm_ntp_server` var and set default to `time.nist.gov`
=> Add variable to handle NTP server

changelogs/fragments/91__fix_unused_var.yml, roles/provision_vcenter/templates/config_parts/vm.j2
Var for `provision_vcenter_vm_network_ip_family` was already defined with a default value, but was not used in the template. This PR fixes this.
=> Add missing var to template

changelogs/fragments/97_swap_community_vcls_for_vmware.yml, galaxy.yml, roles/cluster_settings/README.md, roles/cluster_settings/tasks/main.yml, tests/integration/requirements.txt
Replace community.vmware.vmware_cluster_vcls with vmware.vmware.cluster_vcls
This also removes the pyvmomi<7.0.3 restriction that was on the repo
=> use vmware.vmware.cluster_vcls instead of community

extensions/experiences/README.md, extensions/experiences/load_experience.yml, extensions/experiences/vmware_ops/README.md, extensions/experiences/vmware_ops/setup.yml
This is a basic `setup.yml` for the AAP "Experiences" which helps bootstrap example playbooks and resources for new users.
This only creates one job template because we have other tickets related to playbook naming/structure. So I think we should do those first and then add more job templates here.
=> add experience setup

changelogs/fragments/99_deploy_ovf_template_required_var.yml, roles/deploy_ovf/tasks/input_validation.yml, roles/deploy_ovf/tasks/main.yml
This makes the deploy_ovf pre-check assertions a little easier to read by breaking them up.
It also makes the deploy_ovf_template variable optional in the case that the user has set the deploy_ovf_url and is not using content libraries as a source. Previously, it was always mandatory which is not accurate
=> deploy_ovf_template should not always be mandatory

changelogs/fragments/105-fix-variables in-export-vm-as-ovf.yml, roles/export_vm_as_ovf/README.md, roles/export_vm_as_ovf/tasks/main.yml, tests/integration/targets/vmware_ops_export_vm_as_ovf_test/tasks/main.yml, tests/integration/targets/vmware_ops_export_vm_as_ovf_test/vars/main.yml
This change is from the testathon feedback.
It includes two issues:
1. The documentation for the export_vm_as_ovf role had duplicate and unused variables defined
2. The role uses a `_name` suffix on the datacenter variable that is inconsistent with other roles.
I updated the docs and changed the variable to match other roles, while keeping the old variable name valid
=> Mm feature/fix export vm as ovf vars

changelogs/fragments/106-fix-variable-docs-in-manage-folder.yml, roles/manage_folder/README.md, roles/manage_folder/tasks/main.yml, roles/manage_folder/tasks/manage_path_part.yml, tests/integration/targets/vmware_ops_manage_folder_test/tasks/main.yml, tests/integration/targets/vmware_ops_manage_folder_test/vars.yml, tests/integration/targets/vmware_ops_manage_folder_test/vars/main.yml
This change is from the testathon feedback.
It includes two issues:
1. The documentation for the manage_folder role had the datacenter variable in the wrong section
2. I noticed the datacenter for this role is inconsistent with other roles. So i fixed that too
I updated the docs and changed the variable to match other roles, while keeping the old variable name valid
=> move datacenter out of auth vars for manage_folder

README.md, changelogs/fragments/107-document-python-requirements.yml
This is feedback from the testathon.
The python requirements for this collection are not listed on the Hub dependency page. We cant control that but we can make it more obvious in the collection readme/main documentation where python requirements are documented and can be found.
=> Make python requirements more obvious

changelogs/fragments/111-remove-info-validate-certs-default.yml, roles/info/defaults/main.yml, roles/info/tasks/appliance_info.yml, roles/info/tasks/cluster_info.yml, roles/info/tasks/guest_info.yml, roles/info/tasks/license_info.yml, roles/info/tasks/storage_info.yml
Removing default value for the `info` role's validate certs option. This value is redundant (the default for the modules inside the role is true anyway) and the other roles in this repo do not specify a default.
=> remove validate certs default for info role

changelogs/fragments/113-update-cluster-info-refs.yml, roles/info/tasks/cluster_info.yml, tests/integration/targets/vmware_ops_cluster_settings_test/tasks/main.yml
Updating info role and tests to use the new version of vmware.vmware.cluster_info
=> update cluster_info refs from community to vmware

tests/integration/targets/vmware_ops_esxi_maintenance_mode_test/tasks/main.yml, tests/integration/targets/vmware_ops_vcenter_host_connection_test/tasks/main.yml
Fixed `prepare_deploy_esxi_host` tasks call in order to run it with AAP.
Previously tests failed with error:
`ERROR! the role 'prepare_deploy_esxi_host' was not found in /runner/project/roles:/runner/requirements_roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/runner/project`
=> Fixed prepare_deploy_esxi_host tasks call in order to run it with AAP
